# Generated by Django 5.2.2 on 2025-06-13 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chat Log', 'verbose_name_plural': 'Chat Logs'},
        ),
        migrations.AddField(
            model_name='chatlog',
            name='ai_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='model_name',
            field=models.CharField(default='deepseek-r1:1.5b', max_length=100),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='user_prompt',
            field=models.TextField(blank=True),
        ),
    ]
