# Generated by Django 5.2.3 on 2025-06-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatlog_options_chatlog_ai_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='model_name',
            field=models.CharField(default='deepseek-bakery-expert', max_length=100),
        ),
    ]
